spring.application.name=ledger
server.servlet.context-path=/ledger-tx

#Hibernate - disabled, because we have flyway
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway
spring.datasource.url=jdbc:postgresql://localhost:5432/corebankdb
spring.datasource.username=postgres
spring.datasource.password=corebankpw
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#JOOQ
